In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Create an imbalanced binary classification dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=2, n_redundant=8, 
                           weights=[0.9, 0.1], flip_y=0, random_state=42)

classes, counts = np.unique(y, return_counts=True)
total = counts.sum()
percentages = (counts / total) * 100

# Imprimir resultados
print(f"Clase 0: {percentages[0]:.1f}% ({counts[0]} muestras)")
print(f"Clase 1: {percentages[1]:.1f}% ({counts[1]} muestras)")

Clase 0: 90.0% (900 muestras)
Clase 1: 10.0% (100 muestras)


In [3]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

In [4]:
smt = SMOTE(random_state=42)
X_train_res, y_train_res = smt.fit_resample(X_train, y_train)

classes, counts = np.unique(y_train_res, return_counts=True)
total = counts.sum()
percentages = (counts / total) * 100

# Imprimir resultados
print(f"Clase 0: {percentages[0]:.1f}% ({counts[0]} muestras)")
print(f"Clase 1: {percentages[1]:.1f}% ({counts[1]} muestras)")

Clase 0: 50.0% (630 muestras)
Clase 1: 50.0% (630 muestras)


Vamos a entrenar 4 modelos diferentes:
1. Regresión Logística
2. Random Forest
3. XGBoost
4. XGBoost con SMOTE

In [5]:
models = [
    (
        "Logistic Regression", 
        LogisticRegression(C=1, solver='liblinear'), 
        (X_train, y_train),
        (X_test, y_test),
        {"C": 1, "solver": "liblinear"}
    ),
    (
        "Random Forest", 
        RandomForestClassifier(n_estimators=30, max_depth=3), 
        (X_train, y_train),
        (X_test, y_test),
        {"n_estimators": 30, "max_depth": 3}
    ),
    (
        "XGBClassifier",
        XGBClassifier(use_label_encoder=False, eval_metric='logloss'), 
        (X_train, y_train),
        (X_test, y_test),
        {"use_label_encoder": False, "eval_metric": "logloss"}
    ),
    (
        "XGBClassifier With SMOTE",
        XGBClassifier(use_label_encoder=False, eval_metric='logloss'), 
        (X_train_res, y_train_res),
        (X_test, y_test),
        {"use_label_encoder": False, "eval_metric": "logloss", "resampling": "SMOTE"}
    )
]

In [6]:
reports = []

for model_name, model, train_set, test_set, params in models:
    X_train = train_set[0]
    y_train = train_set[1]
    X_test = test_set[0]
    y_test = test_set[1]
    
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    report = classification_report(y_test, y_pred, output_dict=True)
    print(model_name, "\n", report)
    reports.append(report)

Logistic Regression 
 {'0': {'precision': 0.9454545454545454, 'recall': 0.9629629629629629, 'f1-score': 0.9541284403669725, 'support': 270.0}, '1': {'precision': 0.6, 'recall': 0.5, 'f1-score': 0.5454545454545454, 'support': 30.0}, 'accuracy': 0.9166666666666666, 'macro avg': {'precision': 0.7727272727272727, 'recall': 0.7314814814814814, 'f1-score': 0.749791492910759, 'support': 300.0}, 'weighted avg': {'precision': 0.9109090909090909, 'recall': 0.9166666666666666, 'f1-score': 0.91326105087573, 'support': 300.0}}
Random Forest 
 {'0': {'precision': 0.96415770609319, 'recall': 0.9962962962962963, 'f1-score': 0.9799635701275046, 'support': 270.0}, '1': {'precision': 0.9523809523809523, 'recall': 0.6666666666666666, 'f1-score': 0.7843137254901961, 'support': 30.0}, 'accuracy': 0.9633333333333334, 'macro avg': {'precision': 0.9582693292370712, 'recall': 0.8314814814814815, 'f1-score': 0.8821386478088503, 'support': 300.0}, 'weighted avg': {'precision': 0.9629800307219661, 'recall': 0.9633

In [7]:
reports

[{'0': {'precision': 0.9454545454545454,
   'recall': 0.9629629629629629,
   'f1-score': 0.9541284403669725,
   'support': 270.0},
  '1': {'precision': 0.6,
   'recall': 0.5,
   'f1-score': 0.5454545454545454,
   'support': 30.0},
  'accuracy': 0.9166666666666666,
  'macro avg': {'precision': 0.7727272727272727,
   'recall': 0.7314814814814814,
   'f1-score': 0.749791492910759,
   'support': 300.0},
  'weighted avg': {'precision': 0.9109090909090909,
   'recall': 0.9166666666666666,
   'f1-score': 0.91326105087573,
   'support': 300.0}},
 {'0': {'precision': 0.96415770609319,
   'recall': 0.9962962962962963,
   'f1-score': 0.9799635701275046,
   'support': 270.0},
  '1': {'precision': 0.9523809523809523,
   'recall': 0.6666666666666666,
   'f1-score': 0.7843137254901961,
   'support': 30.0},
  'accuracy': 0.9633333333333334,
  'macro avg': {'precision': 0.9582693292370712,
   'recall': 0.8314814814814815,
   'f1-score': 0.8821386478088503,
   'support': 300.0},
  'weighted avg': {'prec

➡️ Vamos a registrar las métricas y modelos en MLflow

In [8]:
import mlflow
import mlflow.sklearn
import mlflow.xgboost
from mlflow.models.signature import infer_signature

In [9]:
params

{'use_label_encoder': False, 'eval_metric': 'logloss', 'resampling': 'SMOTE'}

In [11]:
mlflow.set_experiment("Second Experiment")
mlflow.set_tracking_uri("http://localhost:5000")

for i, element in enumerate(models):
    model_name = element[0]
    model = element[1]
    X_train, y_train = element[2]
    X_test, y_test = element[3]
    params = element[4]
    report = reports[i]
    
    with mlflow.start_run(run_name=model_name):   
        # Log de hiperparámetros y nombre del modelo     
        mlflow.log_param("model", model_name)
        mlflow.log_params(params)
        
        # Log de todas las métricas
        for label, metrics in report.items():
            if isinstance(metrics, dict):
                for metric_name, value in metrics.items():
                    mlflow.log_metric(f"{label}_{metric_name}", value)
            else:
                mlflow.log_metric(label, metrics)
                
        # Log del dataset
        X_train_df = pd.DataFrame(X_train, columns=[f"feature_{i}" for i in range(X_train.shape[1])])
        X_train_df["label"] = y_train
        dataset_path = f"data/train_dataset_{model_name.replace(' ', '_')}.csv"
        X_train_df.to_csv(dataset_path, index=False)
        mlflow.log_artifact(dataset_path, artifact_path="datasets")
        mlflow.set_tag("dataset", "with_smote") if "SMOTE" in model_name else mlflow.set_tag("dataset", "original")

        # Log del modelo
        input_example = pd.DataFrame(X_test[:2], columns=[f"feature_{i}" for i in range(X.shape[1])])    
        signature = infer_signature(X_test, y_pred)
        
        if "XGB" in model_name:
            mlflow.xgboost.log_model(model, 
                                     "model", 
                                     input_example = input_example, 
                                     signature = signature)
        else:
            mlflow.sklearn.log_model(model, 
                                     "model",
                                     input_example = input_example, 
                                     signature = signature)  

2025/03/26 14:50:11 INFO mlflow.tracking.fluent: Experiment with name 'Second Experiment' does not exist. Creating a new experiment.


🏃 View run Logistic Regression at: http://localhost:5000/#/experiments/422036461495027387/runs/19c2ce1c07b54852888a54c2ec4a913a
🧪 View experiment at: http://localhost:5000/#/experiments/422036461495027387
🏃 View run Random Forest at: http://localhost:5000/#/experiments/422036461495027387/runs/290ab4a614fa41ec9f15a2f5b54e4e5d
🧪 View experiment at: http://localhost:5000/#/experiments/422036461495027387
🏃 View run XGBClassifier at: http://localhost:5000/#/experiments/422036461495027387/runs/540c2b37a171441d99eeab7a1ec9e6b1
🧪 View experiment at: http://localhost:5000/#/experiments/422036461495027387
🏃 View run XGBClassifier With SMOTE at: http://localhost:5000/#/experiments/422036461495027387/runs/fbed176f05ca4baaa8f52513ecabfcc2
🧪 View experiment at: http://localhost:5000/#/experiments/422036461495027387


### 1. Registrar el Modelo

In [18]:
model_name = 'XGB-Smote' # Unique way to call our model
run_id=input('Please type RunID')
model_uri = f'runs:/{run_id}/model'

with mlflow.start_run(run_id=run_id):
    mlflow.register_model(model_uri=model_uri, name=model_name)

Successfully registered model 'XGB-Smote'.
2025/03/26 15:27:08 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: XGB-Smote, version 1


🏃 View run XGBClassifier With SMOTE at: http://localhost:5000/#/experiments/422036461495027387/runs/fbed176f05ca4baaa8f52513ecabfcc2
🧪 View experiment at: http://localhost:5000/#/experiments/422036461495027387


Created version '1' of model 'XGB-Smote'.


💡 Si corremos la celda anterior nuevamente, vamos a estar cambiando de versión al modelo.

#### 🏷️ Aliases comunes en el Model Registry

Cuando registramos modelos en el **Model Registry** de MLflow, podemos asignarles **etiquetas (aliases)** para indicar su rol dentro del ciclo de vida del proyecto.

Algunos alias comunes:

- **Champion**: es el **modelo actual en producción**, el mejor hasta el momento.
- **Challenger**: es un **modelo nuevo que compite** con el Champion. Se lo entrena y evalúa para ver si lo supera.
- **Staging**: modelo en etapa de pruebas, listo para ser validado antes de pasarlo a producción.
- **Archived**: modelos viejos que ya no se usan, pero que quedan guardados para referencia o auditoría.

💡 Usar estos nombres no es obligatorio, pero es una **convención muy útil** para que todo el equipo entienda rápidamente el rol de cada modelo registrado.

### 2. Generar predicciones con el modelo *Challenger*

Ahora vamos a cargar el modelo que registramos como **Challenger** desde el **Model Registry** de MLflow y vamos a **testearlo localmente**.

Esto nos permite, por ejemplo:
- Validar su performance con datos nuevos
- Compararlo contra el modelo actual en producción (el *Champion*)
- Decidir si vale la pena promoverlo a producción


In [19]:
model_version = 1
model_uri = f"models:/{model_name}/{model_version}"

loaded_model = mlflow.xgboost.load_model(model_uri)
y_pred = loaded_model.predict(X_test)
y_pred[:4]

array([0, 0, 0, 0])

Otra opcion usando el alias en lugar del model_version:

In [27]:
model_uri = f"models:/{model_name}@challenger"

loaded_model = mlflow.xgboost.load_model(model_uri)
y_pred = loaded_model.predict(X_test)
y_pred[:4]

array([0, 0, 0, 0])

### 3. Transicionar el modelo a Producción

Usamos MLflowClient

In [28]:
dev_model_uri = f"models:/{model_name}@challenger"
production_model_name = "anomaly-detection-prod"

client = mlflow.MlflowClient()
client.copy_model_version(src_model_uri=dev_model_uri, dst_name=production_model_name)

Successfully registered model 'anomaly-detection-prod'.
Copied version '1' of model 'XGB-Smote' to version '1' of model 'anomaly-detection-prod'.


<ModelVersion: aliases=[], creation_timestamp=1743014400280, current_stage='None', description='', last_updated_timestamp=1743014400280, name='anomaly-detection-prod', run_id='fbed176f05ca4baaa8f52513ecabfcc2', run_link='', source='models:/XGB-Smote/1', status='READY', status_message=None, tags={}, user_id='', version='1'>

➡️ Ahora le podemos dar un alias en la UI, como `"champion"`


Una vez que ya tenemos identificado y probado nuestro modelo Champion, podríamos por ejemplo, empaquetarlo dentro de un contenedor Docker.

Además, hay muchas plataformas que **integran nativamente con MLflow**, como por ejemplo:

- **Databricks**
- **AWS SageMaker**
- **Azure ML**
- **Google Cloud Vertex AI**
- Y otras plataformas open source que aceptan modelos MLflow.

Esto nos permite tener un flujo de trabajo completo: desde la experimentación hasta el despliegue, todo trazable y reproducible.


In [ ]:
# ➡️ Una vez que ya le di el alias @champion, genero predicciones con el modelo en producción 
model_version = 1
prod_model_uri = f"models:/{production_model_name}@champion"

loaded_model = mlflow.xgboost.load_model(prod_model_uri)
y_pred = loaded_model.predict(X_test)
y_pred[:4]

array([0, 0, 0, 0])